[build]
  command = "npm run build"
  publish = "dist"

# Proxy API requests to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://medavicdemo-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Pengaturan untuk SPA routing (must come after the API redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
